import{a as g,S as y,i as c}from"./assets/vendor-ee72e1a4.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const v="https://pixabay.com/api/",L="44710644-2154e124280f212c40f530ba7";async function w(e,o=1){try{return(await g.get(v,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const x=new y(".gallery-list a",{captions:!0,captionsData:"alt",captionsDelay:250});function S(e){const o=document.querySelector(".gallery-list");let a=e.hits.map(s=>`<div class="image-wrapper">
    <a href="${s.largeImageURL}">
    <img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${s.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${s.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${s.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${s.downloads}</p></div>
    </div>
    </div>`).join("");o.insertAdjacentHTML("beforeend",a),x.refresh()}function b(){const e=document.querySelector(".gallery-list");e.innerHTML=""}const p=document.querySelector(".form-gallery"),q=document.querySelector(".form-gallery-input"),l=document.querySelector(".loader"),d=document.querySelector(".load-more"),u=document.querySelector(".scroll-to-top");let i=1,h="";p.addEventListener("submit",T);d.addEventListener("click",E);u.addEventListener("click",R);async function T(e){e.preventDefault(),b(),l.classList.remove("hidden"),h=q.value.trim(),i=1,await m(),p.reset()}async function E(){i+=1,await m()}async function m(){try{const e=await w(h,i);if(l.classList.add("hidden"),e.total===0||h===""){c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}S(e),e.hits.length===0||i*15>=e.totalHits?(d.classList.add("hidden"),c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):d.classList.remove("hidden"),P(),f()}catch{l.classList.add("hidden"),c.error({position:"topRight",message:"An error occurred while fetching images. Please try again later."})}}function P(){const{height:e}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function f(){window.scrollY>1e3?u.classList.remove("hidden"):u.classList.add("hidden")}function R(){window.scrollTo({top:0,behavior:"auto"})}window.addEventListener("scroll",f);
//# sourceMappingURL=commonHelpers.js.map
